### ISSUE TITLE
Create a world similar to the grass field that I bought on amazon. Similar to robocup, but just smaller. The net is the same

### ISSUE THREAD

**Issue by Vuwij** [utra-robosoccer/soccer_description#7]
Create a world file that is same as robocup.world, except with only one net and a grass field of 6x8 feet. There is white paint over the field

The video for the field can be found here.

https://github.com/utra-robosoccer/soccer-vision/tree/8baf04e719d391e58ede65676047f71aa875e1d2/media/videos

The paint is the same thickness.

You also need to create a new net that doesn't have the back posts and has dimensions similar to the one I built in the video. The dimensions are 6 feet apart and 3 feet up. Remove the back posts, only need the front one.

**Comment by zhan4512** [comment]
I completed my task and I am good at coding :)
